<?xml version="1.0"?>
<testResults>
  <FitNesseVersion>v20140122</FitNesseVersion>
  <rootPath>DbFit.AnonymousBlock</rootPath>
    <result>
    <counts>
      <right>0</right>
      <wrong>0</wrong>
      <ignores>0</ignores>
      <exceptions>4</exceptions>
    </counts>
    <runTimeInMillis>3846</runTimeInMillis>
    <content>&lt;br/&gt;&lt;span class="meta"&gt;classpath: lib/*.jar&lt;/span&gt;&lt;br/&gt;&lt;br/&gt;&lt;table&gt;
	&lt;tr&gt;
		&lt;td&gt;import fixture&lt;/td&gt;
	&lt;/tr&gt;
	&lt;tr&gt;
		&lt;td&gt;dbfit.fixture&lt;/td&gt;
	&lt;/tr&gt;
&lt;/table&gt;
&lt;br/&gt;&lt;table&gt;
	&lt;tr&gt;
		&lt;td&gt;DatabaseEnvironment&lt;/td&gt;
		&lt;td colspan="4"&gt;oracle&lt;/td&gt;
	&lt;/tr&gt;
	&lt;tr&gt;
		&lt;td&gt;connect&lt;/td&gt;
		&lt;td&gt;127.0.0.1:7771&lt;/td&gt;
		&lt;td&gt;CID_OWNER&lt;/td&gt;
		&lt;td&gt;cid_owner&lt;/td&gt;
		&lt;td&gt;CDPDVS01&lt;/td&gt;
	&lt;/tr&gt;
&lt;/table&gt;
&lt;br/&gt;&lt;table&gt;
	&lt;tr&gt;
		&lt;td&gt;DatabaseEnvironment&lt;/td&gt;
		&lt;td colspan="4"&gt;oracle&lt;/td&gt;
	&lt;/tr&gt;
	&lt;tr&gt;
		&lt;td class="error"&gt;connect&lt;hr&gt;&lt;pre&gt;&lt;div class="fit_stacktrace"&gt;java.sql.SQLException: Listener refused the connection with the following error:
ORA-12505, TNS:listener does not currently know of SID given in connect descriptor

	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:113)
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:263)
	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:389)
	at oracle.jdbc.driver.PhysicalConnection.&lt;init&gt;(PhysicalConnection.java:454)
	at oracle.jdbc.driver.T4CConnection.&lt;init&gt;(T4CConnection.java:165)
	at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:35)
	at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:802)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at dbfit.api.AbstractDbEnvironment.connect(AbstractDbEnvironment.java:50)
	at dbfit.api.AbstractDbEnvironment.connect(AbstractDbEnvironment.java:78)
	at dbfit.fixture.DatabaseEnvironment.connect(DatabaseEnvironment.java:52)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at fitlibrary.closure.MethodClosure.invoke(MethodClosure.java:31)
	at fitlibrary.closure.MethodClosure.invokeTyped(MethodClosure.java:24)
	at fitlibrary.closure.CalledMethodTarget.invokeTyped(CalledMethodTarget.java:67)
	at fitlibrary.closure.CalledMethodTarget.invokeTyped(CalledMethodTarget.java:82)
	at fitlibrary.closure.CalledMethodTarget.invokeAndWrap(CalledMethodTarget.java:242)
	at fitlibrary.traverse.workflow.caller.ActionCaller.run(ActionCaller.java:25)
	at fitlibrary.traverse.workflow.DoTraverseInterpreter.interpretRow(DoTraverseInterpreter.java:152)
	at fitlibrary.traverse.workflow.DoTraverseInterpreter.interpretAfterFirstRow(DoTraverseInterpreter.java:64)
	at fitlibrary.traverse.workflow.DoTraverseInterpreter.interpretInFlow(DoTraverseInterpreter.java:132)
	at fitlibrary.DoFixture.interpretAfterFirstRow(DoFixture.java:46)
	at fitlibrary.FitLibraryFixture.doTable(FitLibraryFixture.java:75)
	at dbfit.fixture.DatabaseEnvironment.doTable(DatabaseEnvironment.java:22)
	at fit.Fixture.interpretFollowingTables(Fixture.java:120)
	at fit.Fixture.interpretTables(Fixture.java:106)
	at fit.Fixture.doTables(Fixture.java:80)
	at fit.FitServer.process(FitServer.java:81)
	at fit.FitServer.run(FitServer.java:56)
	at fit.FitServer.main(FitServer.java:41)
&lt;/div&gt;&lt;/pre&gt;&lt;/td&gt;
		&lt;td&gt;127.0.0.1:7771&lt;/td&gt;
		&lt;td&gt;CID_OWNER&lt;/td&gt;
		&lt;td&gt;cid_owner&lt;/td&gt;
		&lt;td&gt;CDPDVR01&lt;/td&gt;
	&lt;/tr&gt;
&lt;/table&gt;
&lt;br/&gt;&lt;table&gt;
	&lt;tr&gt;
		&lt;td class="error"&gt;Execute Procedure&lt;hr&gt;&lt;pre&gt;&lt;div class="fit_stacktrace"&gt;java.lang.Error: java.lang.IllegalArgumentException: No open connection to a database is available. Make sure your database is running and that you have connected before performing any queries.
	at dbfit.fixture.DbObjectExecutionFixture.doRows(DbObjectExecutionFixture.java:80)
	at fit.Fixture.doTable(Fixture.java:154)
	at fit.Fixture.interpretFollowingTables(Fixture.java:120)
	at fit.Fixture.interpretTables(Fixture.java:106)
	at fit.Fixture.doTables(Fixture.java:80)
	at fit.FitServer.process(FitServer.java:81)
	at fit.FitServer.run(FitServer.java:56)
	at fit.FitServer.main(FitServer.java:41)
Caused by: java.lang.IllegalArgumentException: No open connection to a database is available. Make sure your database is running and that you have connected before performing any queries.
	at dbfit.api.AbstractDbEnvironment.checkConnectionValid(AbstractDbEnvironment.java:221)
	at dbfit.api.AbstractDbEnvironment.getConnection(AbstractDbEnvironment.java:146)
	at dbfit.api.DbStoredProcedureCall.toStatementExecution(DbStoredProcedureCall.java:54)
	at dbfit.api.DbStoredProcedure.buildPreparedStatement(DbStoredProcedure.java:27)
	at dbfit.fixture.DbObjectExecutionFixture.doRows(DbObjectExecutionFixture.java:64)
	... 7 more
&lt;/div&gt;&lt;/pre&gt;&lt;/td&gt;
		&lt;td&gt;Test&lt;/td&gt;
	&lt;/tr&gt;
&lt;/table&gt;
Create or REPLACE PROCEDURE Test&lt;br/&gt;is&lt;br/&gt;CURSOR c (p_tgt_sch VARCHAR2) is &lt;br/&gt;SELECT table_name &lt;br/&gt;FROM dba_tables &lt;br/&gt;WHERE table_name IN &lt;br/&gt;(&lt;br/&gt;'ADDRESS_TYPES'                 &lt;br/&gt;)&lt;br/&gt;&lt;strike&gt;and owner = p_tgt_sch&lt;br/&gt;;&lt;br/&gt;&lt;br/&gt;v_err_msg varchar2(3000);&lt;br/&gt;v_stmt varchar2(3000);&lt;br/&gt;v_stmt1 varchar2(3000);&lt;br/&gt;v_cnt number := 1;&lt;br/&gt;v_row_cnt number:=0;&lt;br/&gt;v_src_sch varchar2(300) := 'BRP_OWNER';&lt;br/&gt;v_tgt_sch varchar2(300) := 'BRP_OWNER_PROD';&lt;br/&gt;&lt;br/&gt;BEGIN&lt;br/&gt;&lt;br/&gt;FOR rec IN c (v_tgt_sch)&lt;br/&gt;&lt;br/&gt;LOOP&lt;br/&gt;    BEGIN&lt;br/&gt;    v_stmt1 := 'select count(1) from '|| v_tgt_sch||'.'||rec.table_name||' where rownum = 1 ';&lt;br/&gt;    DBMS_OUTPUT.PUT_LINE('stmt1:'||v_stmt1);&lt;br/&gt;    &lt;/strike&gt; EXECUTE IMMEDIATE 'select count(1) into v_cnt from '||rec.table_name||' where rownum = 1 ';&lt;strike&gt; returning into v_cnt;&lt;br/&gt;    EXECUTE IMMEDIATE v_stmt1 into v_cnt;&lt;br/&gt;     if v_cnt=0 then&lt;br/&gt;    v_stmt := 'insert /*+ APPEND */ into '|| v_tgt_sch||'.'||rec.table_name ||'(select * from '|| v_src_sch||'.'||rec.table_name ||')';&lt;br/&gt;    &lt;/strike&gt;DBMS_OUTPUT.PUT_LINE('inside if');&lt;br/&gt;    EXECUTE IMMEDIATE v_stmt;&lt;br/&gt;    v_row_cnt:=sql%rowcount;&lt;br/&gt;      dbms_output.Put_line(' Number of record inserted : '||v_row_cnt);&lt;br/&gt;    &lt;br/&gt;   --DBMS_OUTPUT.PUT_LINE('inside if 2');&lt;br/&gt;    COMMIT;&lt;br/&gt;    &lt;br/&gt;    ELSE&lt;br/&gt;     dbms_output.put_line(' Data already present in Table name  '||rec.table_name);&lt;br/&gt;    END IF;&lt;br/&gt;      &lt;br/&gt;    EXCEPTION&lt;br/&gt;    WHEN OTHERS THEN&lt;br/&gt;        v_err_msg := SUBSTR(SQLERRM,1,200);&lt;br/&gt;        DBMS_OUTPUT.PUT_LINE(' Following error occurred for table '||rec.table_name||' : '||v_err_msg);&lt;br/&gt;    &lt;br/&gt;    END;&lt;br/&gt;  &lt;br/&gt;END LOOP;&lt;br/&gt;END;|&lt;br/&gt;&lt;table&gt;
	&lt;tr&gt;
		&lt;td class="error"&gt;Execute&lt;hr&gt;&lt;pre&gt;&lt;div class="fit_stacktrace"&gt;java.lang.Error: java.lang.IllegalArgumentException: No open connection to a database is available. Make sure your database is running and that you have connected before performing any queries.
	at dbfit.fixture.Execute.doRows(Execute.java:29)
	at fit.Fixture.doTable(Fixture.java:154)
	at fit.Fixture.interpretFollowingTables(Fixture.java:120)
	at fit.Fixture.interpretTables(Fixture.java:106)
	at fit.Fixture.doTables(Fixture.java:80)
	at fit.FitServer.process(FitServer.java:81)
	at fit.FitServer.run(FitServer.java:56)
	at fit.FitServer.main(FitServer.java:41)
Caused by: java.lang.IllegalArgumentException: No open connection to a database is available. Make sure your database is running and that you have connected before performing any queries.
	at dbfit.api.AbstractDbEnvironment.checkConnectionValid(AbstractDbEnvironment.java:221)
	at dbfit.api.AbstractDbEnvironment.getConnection(AbstractDbEnvironment.java:146)
	at dbfit.api.AbstractDbEnvironment.createStatementWithBoundFixtureSymbols(AbstractDbEnvironment.java:108)
	at dbfit.api.DbStatement.buildPreparedStatement(DbStatement.java:23)
	at dbfit.fixture.Execute.doRows(Execute.java:26)
	... 7 more
&lt;/div&gt;&lt;/pre&gt;&lt;/td&gt;
		&lt;td&gt;commit&lt;/td&gt;
	&lt;/tr&gt;
&lt;/table&gt;
&lt;br/&gt;&lt;table&gt;
	&lt;tr&gt;
		&lt;td class="error"&gt;Query&lt;hr&gt;&lt;pre&gt;&lt;div class="fit_stacktrace"&gt;java.lang.IllegalArgumentException: No open connection to a database is available. Make sure your database is running and that you have connected before performing any queries.
	at dbfit.api.AbstractDbEnvironment.checkConnectionValid(AbstractDbEnvironment.java:221)
	at dbfit.api.AbstractDbEnvironment.getConnection(AbstractDbEnvironment.java:146)
	at dbfit.api.AbstractDbEnvironment.createStatementWithBoundFixtureSymbols(AbstractDbEnvironment.java:108)
	at dbfit.fixture.Query.getDataTable(Query.java:43)
	at dbfit.fixture.RowSetFixture.doRows(RowSetFixture.java:87)
	at fit.Fixture.doTable(Fixture.java:154)
	at fit.Fixture.interpretFollowingTables(Fixture.java:120)
	at fit.Fixture.interpretTables(Fixture.java:106)
	at fit.Fixture.doTables(Fixture.java:80)
	at fit.FitServer.process(FitServer.java:81)
	at fit.FitServer.run(FitServer.java:56)
	at fit.FitServer.main(FitServer.java:41)
&lt;/div&gt;&lt;/pre&gt;&lt;/td&gt;
		&lt;td&gt;Select * from BRP_OWNER.ADDRESS_TYPES&lt;/td&gt;
	&lt;/tr&gt;
	&lt;tr&gt;
		&lt;td&gt;adt_address_type&lt;/td&gt;
		&lt;td&gt;adt_address_type_desc&lt;/td&gt;
	&lt;/tr&gt;
	&lt;tr&gt;
		&lt;td&gt;DEL_MIG&lt;/td&gt;
		&lt;td&gt;Delivery (Migrant)&lt;/td&gt;
	&lt;/tr&gt;
	&lt;tr&gt;
		&lt;td&gt;DEL_REP&lt;/td&gt;
		&lt;td&gt;Delivery (Representative)&lt;/td&gt;
	&lt;/tr&gt;
	&lt;tr&gt;
		&lt;td&gt;DEL_RETURN&lt;/td&gt;
		&lt;td&gt;Delivery (Returned Cards)&lt;/td&gt;
	&lt;/tr&gt;
&lt;/table&gt;
&lt;br/&gt;</content>
    <relativePageName>AnonymousBlock</relativePageName>
    
    
    
  </result>
  
    <finalCounts>
    <right>0</right>
    <wrong>0</wrong>
    <ignores>0</ignores>
    <exceptions>1</exceptions>
  </finalCounts>
  <totalRunTimeInMillis>5139</totalRunTimeInMillis>
  
</testResults>

